services:
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - 5108:8002
    volumes:
      - $MUSIC_DIR:/app/media:rw
      - ./data:/app/data
    restart: unless-stopped
networks: {}
