services:
  filebrowser_quantum:
    image: gtstef/filebrowser:latest # Quantum 分支的镜像
    container_name: filebrowser-quantum
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - <changeme>:/srv # 挂载数据目录
      - ./data:/config # 挂载配置目录
    ports:
      - 5100:80
    restart: unless-stopped
networks: {}
