services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - 5103:4533
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./data:/data
      - $MUSIC_DIR:/music:ro # 注意音乐文件夹是ro即只读的，Navidrome 不需要也不会对你的音乐库实际文件进行任何修改操作
networks: {}
