services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    ports:
      - 5102:5230
    volumes:
      - ./data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=5230
    restart: unless-stopped
networks: {}
