services:
  searxng:
    image: searxng/searxng:latest
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./config/:/etc/searxng/
    ports:
      - 5104:8080
    env_file:
      - ./.env
    container_name: searxng
networks: {}
